# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infoWidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormInfo(object):
    def setupUi(self, FormInfo):
        FormInfo.setObjectName(_fromUtf8("FormInfo"))
        FormInfo.resize(548, 641)
        self.gridLayout = QtGui.QGridLayout(FormInfo)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_14 = QtGui.QLabel(FormInfo)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 7, 6, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout.addWidget(self.lineEdit_15, 8, 4, 1, 1)
        self.label_17 = QtGui.QLabel(FormInfo)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 9, 1, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout.addWidget(self.lineEdit_12, 6, 8, 1, 1)
        self.label_12 = QtGui.QLabel(FormInfo)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 6, 6, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout.addWidget(self.lineEdit_10, 5, 8, 1, 1)
        self.label_16 = QtGui.QLabel(FormInfo)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 8, 6, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout.addWidget(self.lineEdit_11, 6, 4, 1, 1)
        self.label_15 = QtGui.QLabel(FormInfo)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 8, 1, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout.addWidget(self.lineEdit_9, 5, 4, 1, 1)
        self.label_9 = QtGui.QLabel(FormInfo)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 5, 1, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout.addWidget(self.lineEdit_8, 4, 8, 1, 1)
        self.label_2 = QtGui.QLabel(FormInfo)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 1, 4, 1, 5)
        self.label_10 = QtGui.QLabel(FormInfo)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 5, 6, 1, 1)
        self.lineEdit_20 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.gridLayout.addWidget(self.lineEdit_20, 11, 4, 1, 1)
        self.label_20 = QtGui.QLabel(FormInfo)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 11, 1, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 2, 8, 1, 1)
        self.label_1 = QtGui.QLabel(FormInfo)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout.addWidget(self.label_1, 0, 1, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout.addWidget(self.lineEdit_7, 4, 4, 1, 1)
        self.label_11 = QtGui.QLabel(FormInfo)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 6, 1, 1, 1)
        self.label_19 = QtGui.QLabel(FormInfo)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 10, 1, 1, 1)
        self.label_13 = QtGui.QLabel(FormInfo)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 7, 1, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout.addWidget(self.lineEdit_13, 7, 4, 1, 1)
        self.lineEdit_19 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.gridLayout.addWidget(self.lineEdit_19, 10, 4, 1, 5)
        self.label_5 = QtGui.QLabel(FormInfo)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(FormInfo)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 6, 1, 1)
        self.label_4 = QtGui.QLabel(FormInfo)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 6, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 3, 4, 1, 1)
        self.label_8 = QtGui.QLabel(FormInfo)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 4, 6, 1, 1)
        self.label_3 = QtGui.QLabel(FormInfo)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 2, 4, 1, 1)
        self.label_7 = QtGui.QLabel(FormInfo)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 4, 1, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout.addWidget(self.lineEdit_6, 3, 8, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout.addWidget(self.lineEdit_14, 7, 8, 1, 1)
        self.label_18 = QtGui.QLabel(FormInfo)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 9, 6, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout.addWidget(self.lineEdit_17, 9, 4, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout.addWidget(self.lineEdit_18, 9, 8, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout.addWidget(self.lineEdit_16, 8, 8, 1, 1)
        self.label_21 = QtGui.QLabel(FormInfo)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 12, 1, 1, 1)
        self.label_22 = QtGui.QLabel(FormInfo)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 12, 6, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.gridLayout.addWidget(self.lineEdit_21, 12, 4, 1, 1)
        self.lineEdit_22 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout.addWidget(self.lineEdit_22, 12, 8, 1, 1)
        self.lineEdit_1 = QtGui.QLineEdit(FormInfo)
        self.lineEdit_1.setObjectName(_fromUtf8("lineEdit_1"))
        self.gridLayout.addWidget(self.lineEdit_1, 0, 4, 1, 2)
        self.pushButton = QtGui.QPushButton(FormInfo)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 8, 1, 1)

        self.retranslateUi(FormInfo)
        QtCore.QMetaObject.connectSlotsByName(FormInfo)

    def retranslateUi(self, FormInfo):
        FormInfo.setWindowTitle(_translate("FormInfo", "Information", None))
        self.label_14.setText(_translate("FormInfo", "DibPart", None))
        self.label_17.setText(_translate("FormInfo", "System", None))
        self.label_12.setText(_translate("FormInfo", "Lot", None))
        self.label_16.setText(_translate("FormInfo", "Vendor", None))
        self.label_15.setText(_translate("FormInfo", "DibSerial", None))
        self.label_9.setText(_translate("FormInfo", "Flow", None))
        self.label_2.setText(_translate("FormInfo", "file path", None))
        self.label_10.setText(_translate("FormInfo", "Serial", None))
        self.label_20.setText(_translate("FormInfo", "Result", None))
        self.label_1.setText(_translate("FormInfo", "flow ID/UUID", None))
        self.label_11.setText(_translate("FormInfo", "Kalos2 Site", None))
        self.label_19.setText(_translate("FormInfo", "Users_C", None))
        self.label_13.setText(_translate("FormInfo", "Operator", None))
        self.label_5.setText(_translate("FormInfo", "Tester ID", None))
        self.label_6.setText(_translate("FormInfo", "Date", None))
        self.label_4.setText(_translate("FormInfo", "end line", None))
        self.label_8.setText(_translate("FormInfo", "Device", None))
        self.label_3.setText(_translate("FormInfo", "start Line", None))
        self.label_7.setText(_translate("FormInfo", "Program", None))
        self.label_18.setText(_translate("FormInfo", "Comment", None))
        self.label_21.setText(_translate("FormInfo", "SoftBin", None))
        self.label_22.setText(_translate("FormInfo", "SortBin", None))
        self.pushButton.setText(_translate("FormInfo", "Update Infomation", None))

